[package]
name = "repotool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
git2 = "0.19"
log = "0.4"
octocrab = "0.38"
pretty_env_logger = "0.5"
tokio = { version = "1.38", features = ["rt-multi-thread"] }
